### ISSUE TITLE
Allow device classes to be specified as direct imports

### ISSUE THREAD

**Issue by canismarko** [BCDA-APS/guarneri#6]
## Expected Behavior

It would be nice if we didn't need to always tell the Instrument which devices are fair game. The consumer code can do this if it wants, but to do this for all cases seems like boilerplate.

This should happen after the configuration file is parsed into the common definition list so that it doesn't depend on whether this done in TOML, YAML, or a custom configuration format.

The following example YAML file from @prjemian would then be usable. It would still require that either ``parse_config`` or ``parse_yaml_file`` is subclassed in order to understand the specific structure of the YAML file, but the *device_class* parameter would not need special treatment.

```yaml
class: instrument.devices.temperature_signal.TemperaturePositioner
    kwargs:
      prefix: gp:userCalc8
      egu: C
      limits: [-20, 255]
    wait_for_connection: True
```

``parse_config()`` or ``parse_yaml_file()`` would need to return the following python list:

```python
[
    {
        "device_class": "instrument.devices.temperature_signal.TemperaturePositioner",
        "kwargs": {
            "prefix": "gp:userCalc8",
            "egu": "C",
            "limits": (-20, 255),
        },
    },
...
]
```

*wait_for_connection* might not be necessary since this can be handled by ``Instrument.connect()``, but we can discuss separately.

## Current Behavior

Currently, ``Instrument`` needs a dictionary of device class names and their corresponding Device class or factory:

```python
instrument = Instrument({
    "motor": ophyd.EpicsMotor
})
```

which can then consume this TOML file:

```toml
[[ motor ]]
name = "m1"
prefix = "255idcVME:m1"
```

After parsing, the instrument looks up the section heading "motor" in the list of known device classes:
https://github.com/spc-group/guarneri/blob/25dd1c00952e64fb612a4b459921e226519a2e43/src/guarneri/instrument.py#L158

## Possible Solution

Let's say we have the following TOML:

```toml
[[ ophyd.EpicsMotor ]]
name = "m1"
prefix = "255idcVME:m1"
```

If the key for the device class (i.e. ``"ophyd.EpicsMotor"``) is not in ``device_classes``, then the instrument could attempt to import it directly. I believe @prjemian has a way of doing this already so we can perhaps ~~steal~~ gain inspiration from that solution.

## Context

Having the ability to specify device class names explicitly is useful for customizing the loading operation. But for many use cases this might be considered boiler plate, especially if the device is part of some other library (e.g. apstools) and isn't going to be subclasses or customized. Beamline staff could just add an entry to the configuration file directly using the import path and be done.
